#!/bin/bash

FULL_REQUIRED_GB=30
DIGITAL_REQUIRED_GB=5
SDR_REQUIRED_GB=10
APRS_REQUIRED_GB=3
SATELLITE_REQUIRED_GB=2
PROGRAMMING_REQUIRED_GB=2
SERVER_REQUIRED_GB=8
SAFETY_RESERVE_GB=5

FREE_SPACE_KB=$(df / --output=avail | tail -n 1)
FREE_SPACE_GB=$((FREE_SPACE_KB / 1024 / 1024))
INSTALL_TYPE="$1"

case "$INSTALL_TYPE" in
    FULL) REQUIRED_GB=$FULL_REQUIRED_GB; DISPLAY_NAME="Complete Collection";;
    DIGITAL) REQUIRED_GB=$DIGITAL_REQUIRED_GB; DISPLAY_NAME="Digital Modes";;
    SDR) REQUIRED_GB=$SDR_REQUIRED_GB; DISPLAY_NAME="SDR Software";;
    APRS) REQUIRED_GB=$APRS_REQUIRED_GB; DISPLAY_NAME="APRS and Packet";;
    SATELLITE) REQUIRED_GB=$SATELLITE_REQUIRED_GB; DISPLAY_NAME="Satellite Tools";;
    PROGRAMMING) REQUIRED_GB=$PROGRAMMING_REQUIRED_GB; DISPLAY_NAME="Radio Programming";;
    SERVER) REQUIRED_GB=$SERVER_REQUIRED_GB; DISPLAY_NAME="Server Tools";;
    *) echo "Unknown installation type."; exit 2;;
esac

TOTAL=$((REQUIRED_GB + SAFETY_RESERVE_GB))

echo "Selected: $DISPLAY_NAME"
echo "Free: ${FREE_SPACE_GB} GB"
echo "Estimated install: ${REQUIRED_GB} GB"
echo "Safety reserve: ${SAFETY_RESERVE_GB} GB"

if [ "$FREE_SPACE_GB" -lt "$TOTAL" ]; then
    echo "NOT ENOUGH SPACE"
    exit 1
fi

echo "PASS: Sufficient storage is available."
